"use client";

import { canPerformShipmentAction } from "@/config/shipmentActionPermissions";
import { useAuth } from "@/context/AuthContext";
import { useSystemConfirm } from "@/context/SystemConfirmContext";
import { useSystemNotification } from "@/context/SystemNotificationContext";
import { useLanguage } from "@/context/LanguageContext";
import { recordActivity } from "@/services/activityLogApi";
import { createDatabaseRow, getDatabaseRow, listDatabaseRows, updateDatabaseRow } from "@/services/postgresShipmentApi";
import React, { useEffect, useMemo, useState } from "react";
import { paginateItems } from "@/utils/pagination";
import PaginationControls from "@/components/common/PaginationControls";

type EntityKey = "suppliers" | "carriers" | "warehouses";
type DataRow = Record<string, unknown>;

interface FieldConfig {
  key: string;
  labelKey: string;
  required?: boolean;
  multiline?: boolean;
  autoGenerated?: boolean;
}

interface EntityConfig {
  titleKey: string;
  singularKey: string;
  endpoint: string;
  idField: string;
  fields: FieldConfig[];
}

const DEFAULT_PAGE_SIZE = 15;
const ENTITY_CONFIG: Record<EntityKey, EntityConfig> = {
  suppliers: {
    titleKey: "suppliers",
    singularKey: "supplierLower",
    endpoint: "nha-cung-cap",
    idField: "id_ncc",
    fields: [
      // { key: "id_ncc", labelKey: "supplierCode", autoGenerated: true },
      { key: "ten_ncc", labelKey: "supplierName", required: true },
      { key: "email", labelKey: "email" },
      { key: "quoc_gia", labelKey: "country" },
      { key: "so_dien_thoai", labelKey: "phoneNumber" },
      { key: "dia_chi", labelKey: "address", multiline: true },
    ],
  },
  carriers: {
    titleKey: "carriers",
    singularKey: "carrierLower",
    endpoint: "hang-tau",
    idField: "id_hang_tau",
    fields: [
      // { key: "id_hang_tau", labelKey: "carrierCode", autoGenerated: true },
      { key: "ten_hang_tau", labelKey: "carrierName", required: true },
      { key: "email", labelKey: "email" },
    ],
  },
  warehouses: {
    titleKey: "warehouses",
    singularKey: "warehouseLower",
    endpoint: "kho",
    idField: "id_kho",
    fields: [
      // { key: "id_kho", labelKey: "warehouseCode", autoGenerated: true },
      { key: "ten_kho", labelKey: "warehouseCatalogName", required: true },
      { key: "email", labelKey: "email" },
      { key: "so_dien_thoai", labelKey: "phoneNumber" },
      { key: "dia_chi", labelKey: "address", multiline: true },
    ],
  },
};

function emptyForm(config: EntityConfig): Record<string, string> {
  return Object.fromEntries(config.fields.map((field) => [field.key, ""]));
}

export default function MasterDataPage() {
  const { user } = useAuth();
  const { notify } = useSystemNotification();
  const { confirm } = useSystemConfirm();
  const { t } = useLanguage();
  const canManage = canPerformShipmentAction(user, "manageMasterData");
  const [active, setActive] = useState<EntityKey>("suppliers");
  const [rows, setRows] = useState<DataRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [query, setQuery] = useState("");
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(DEFAULT_PAGE_SIZE);
  const [form, setForm] = useState<Record<string, string>>(() => emptyForm(ENTITY_CONFIG.suppliers));
  const [editingId, setEditingId] = useState<string | null>(null);
  const config = ENTITY_CONFIG[active];

  const loadRows = async () => {
    setLoading(true);
    try {
      setRows(await listDatabaseRows<DataRow>(config.endpoint));
    } catch (error) {
      notify(error instanceof Error ? error.message : t("catalogListLoadError", { catalog: t(config.titleKey) }), "error");
      setRows([]);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (!canManage) return;
    setForm(emptyForm(config));
    setEditingId(null);
    setQuery("");
    setPage(1);
    void loadRows();
    // Chỉ tải lại khi đổi loại danh mục hoặc quyền hiện tại.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [active, canManage]);

  const filteredRows = useMemo(() => {
    const keyword = query.trim().toLocaleLowerCase("vi");
    if (!keyword) return rows;
    return rows.filter((row) => config.fields.some((field) => String(row[field.key] ?? "").toLocaleLowerCase("vi").includes(keyword)));
  }, [config.fields, query, rows]);
  const { totalPages, safePage, items: displayedRows, from, to } = paginateItems(filteredRows, page, pageSize);

  const beginCreate = () => {
    setEditingId(null);
    setForm(emptyForm(config));
  };

  const beginEdit = async (row: DataRow) => {
    const id = String(row[config.idField] ?? "");
    if (!id) return;
    try {
      const latest = await getDatabaseRow<DataRow>(config.endpoint, id);
      setEditingId(id);
      setForm(Object.fromEntries(config.fields.map((field) => [field.key, String(latest[field.key] ?? row[field.key] ?? "")] )));
    } catch (error) {
      notify(error instanceof Error ? error.message : t("catalogItemLoadError", { catalog: t(config.singularKey) }), "error");
    }
  };

  const save = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const missing = config.fields.filter((field) => field.required && !field.autoGenerated && !form[field.key]?.trim());
    if (missing.length > 0) return notify(t("enterRequiredFields", { fields: missing.map((field) => t(field.labelKey)).join(", ") }), "warning");
    const approved = await confirm({
      title: editingId ? t("confirmCatalogEdit", { catalog: t(config.singularKey) }) : t("confirmCatalogAdd", { catalog: t(config.singularKey) }),
      message: editingId ? t("saveChangesFor", { id: editingId }) : t("addCatalogItem", { catalog: t(config.singularKey), id: "tự động" }),
      confirmText: editingId ? t("save") : t("addNew"),
    });
    if (!approved) return;
    setSaving(true);
    try {
      if (editingId) {
        const changes = Object.fromEntries(Object.entries(form).filter(([key]) => key !== config.idField));
        await updateDatabaseRow(config.endpoint, editingId, changes);
      } else {
        const createPayload = Object.fromEntries(Object.entries(form).filter(([key]) => key !== config.idField));
        await createDatabaseRow(config.endpoint, createPayload);
      }
      recordActivity(user, {
        action: editingId ? "UPDATE_MASTER_DATA" : "CREATE_MASTER_DATA",
        location: `/master-data/${config.endpoint}`,
        detail: `${editingId ? "Cập nhật" : "Tạo"} ${t(config.singularKey)} ${editingId || "(ID tự động)"}`,
      });
      notify(editingId ? t("catalogUpdated", { catalog: t(config.singularKey) }) : t("catalogAdded", { catalog: t(config.singularKey) }), "success");
      beginCreate();
      await loadRows();
    } catch (error) {
      notify(error instanceof Error ? error.message : t("catalogSaveError", { catalog: t(config.singularKey) }), "error");
    } finally {
      setSaving(false);
    }
  };

  if (!canManage) {
    return <div className="flex min-h-[55vh] items-center justify-center text-sm font-medium text-error-600">{t("adminAllOnly")}</div>;
  }

  return (
    <section className="space-y-5">
      <div>
        <h1 className="text-2xl font-semibold text-gray-800 dark:text-white/90">{t("masterDataManagement")}</h1>
        <p className="mt-1 text-sm text-gray-500 dark:text-gray-400">{t("masterDataDescription")}</p>
      </div>
      <div className="flex gap-1 overflow-x-auto rounded-xl border border-gray-200 bg-white p-1.5 dark:border-gray-800 dark:bg-white/[0.03]">
        {(Object.keys(ENTITY_CONFIG) as EntityKey[]).map((key) => (
          <button key={key} type="button" onClick={() => setActive(key)} className={`shrink-0 rounded-lg px-4 py-2.5 text-sm font-semibold ${active === key ? "bg-brand-500 text-white" : "text-gray-600 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-800"}`}>{t(ENTITY_CONFIG[key].titleKey)}</button>
        ))}
      </div>
      <div className="grid gap-5 xl:grid-cols-[minmax(0,1.6fr)_minmax(320px,0.8fr)]">
        <div className="overflow-hidden rounded-2xl border border-gray-200 bg-white dark:border-gray-800 dark:bg-white/[0.03]">
          <div className="flex flex-col gap-3 border-b border-gray-100 p-4 dark:border-gray-800 sm:flex-row sm:items-center sm:justify-between">
            <div><h2 className="font-semibold text-gray-800 dark:text-white">{t("catalogList", { catalog: t(config.titleKey) })}</h2><p className="text-xs text-gray-400">{t("dataCount", { count: filteredRows.length })}</p></div>
            <div className="flex gap-2"><input value={query} onChange={(event) => { setQuery(event.target.value); setPage(1); }} placeholder={t("searchPlaceholderShort")} className="h-10 min-w-0 rounded-xl border border-gray-200 bg-gray-50 px-3 text-sm outline-none focus:border-brand-400 dark:border-gray-700 dark:bg-gray-900 dark:text-white" /><button type="button" onClick={() => void loadRows()} className="rounded-xl border border-gray-200 px-3 text-sm font-semibold text-gray-600 dark:border-gray-700 dark:text-gray-300">{t("refreshData")}</button></div>
          </div>
          {loading ? <div className="flex min-h-60 items-center justify-center"><span className="h-9 w-9 animate-spin rounded-full border-2 border-brand-500 border-t-transparent" /></div> : (
            <div className="overflow-x-auto"><table className="w-full min-w-[680px]"><thead className="bg-gray-50 text-left text-xs uppercase text-gray-500 dark:bg-gray-900/50"><tr>{config.fields.map((field) => <th key={field.key} className="px-4 py-3">{t(field.labelKey)}</th>)}<th className="px-4 py-3 text-right">{t("actions")}</th></tr></thead><tbody className="divide-y divide-gray-100 dark:divide-gray-800">{displayedRows.map((row, rowIndex) => <tr key={`${active}-${String(row[config.idField] ?? "row")}-${rowIndex}`} className="hover:bg-gray-50/60 dark:hover:bg-white/[0.02]">{config.fields.map((field) => <td key={field.key} className="max-w-56 truncate px-4 py-3 text-sm text-gray-700 dark:text-gray-300" title={String(row[field.key] ?? "")}>{String(row[field.key] ?? "—")}</td>)}<td className="px-4 py-3 text-right"><button type="button" onClick={() => void beginEdit(row)} className="rounded-lg border border-brand-200 px-3 py-1.5 text-xs font-semibold text-brand-600 hover:bg-brand-50">{t("edit")}</button></td></tr>)}</tbody></table>{displayedRows.length === 0 && <p className="py-10 text-center text-sm text-gray-400">{t("noData")}</p>}</div>
          )}
          {displayedRows.length > 0 && <PaginationControls page={safePage} totalPages={totalPages} pageSize={pageSize} totalItems={filteredRows.length} from={from} to={to} onPageChange={setPage} onPageSizeChange={(value) => { setPageSize(value); setPage(1); }} />}
        </div>
        <form onSubmit={save} className="h-fit rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03]">
          <div className="mb-5 flex items-start justify-between gap-3"><div><h2 className="font-semibold text-gray-800 dark:text-white">{editingId ? t("editCatalog", { catalog: t(config.singularKey) }) : t("addCatalog", { catalog: t(config.singularKey) })}</h2><p className="mt-1 text-xs text-gray-400">{editingId ? editingId : t("enterInformationBelow")}</p></div>{editingId && <button type="button" onClick={beginCreate} className="text-xs font-semibold text-gray-500">{t("cancelEdit")}</button>}</div>
          <div className="space-y-4">{config.fields.filter((field) => !field.autoGenerated || Boolean(editingId)).map((field) => <label key={field.key} className="block text-sm font-medium text-gray-700 dark:text-gray-300">{t(field.labelKey)}{field.required && <span className="text-error-500"> *</span>}{field.autoGenerated && !editingId && <span className="ml-1 text-xs font-normal text-gray-400">(tự động)</span>}{field.multiline ? <textarea value={form[field.key] || ""} disabled={Boolean(editingId && field.key === config.idField)} onChange={(event) => setForm((current) => ({ ...current, [field.key]: event.target.value }))} rows={3} className="mt-1.5 w-full rounded-xl border border-gray-200 bg-gray-50 px-3 py-2 text-sm outline-none focus:border-brand-400 disabled:opacity-60 dark:border-gray-700 dark:bg-gray-900 dark:text-white" /> : <input type={field.key === "email" ? "email" : "text"} value={form[field.key] || ""} disabled={Boolean(editingId && field.key === config.idField)} onChange={(event) => setForm((current) => ({ ...current, [field.key]: event.target.value }))} className="mt-1.5 h-10 w-full rounded-xl border border-gray-200 bg-gray-50 px-3 text-sm outline-none focus:border-brand-400 disabled:opacity-60 dark:border-gray-700 dark:bg-gray-900 dark:text-white" />}</label>)}</div>
          <button type="submit" disabled={saving} className="mt-5 w-full rounded-xl bg-brand-500 px-4 py-2.5 text-sm font-semibold text-white hover:bg-brand-600 disabled:opacity-60">{saving ? t("saving") : editingId ? t("save") : t("addNew")}</button>
        </form>
      </div>
    </section>
  );
}
